version: "3"
services:
  webserver:
    build: ./client
    ports:
      - "80:80"
  mongodb:
    image: "mongo:4.0.6"
    ports: 
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data:/data/db
    command: mongod --auth --dbpath /data/db
  restapi:
    build: ./server
    # links: 
    #   - mongodb
  # mongodb:
  #   image: "mongo:4.0.6"
  #   ports: 
  #     - "27017:27017"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #   volumes:
  #     - ./data:/data/db
  #   command: mongod --auth --dbpath /data/db
